version: '3'

services:
  jira-web:
    depends_on:
    - jira-db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-web
    ports:
      - 8080:8080
    environment:
      # - 'JIRA_DATABASE_URL=jira-db://jira-user@postgresql/jiradb'
      - 'JIRA_DATABASE_URL=jdbc:postgresql://jira-db:5432/jira_db'
      - 'JIRA_USER=jiea_user'
      - 'JIRA_DB_PASSWORD=password'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
    # env_file:
      # - .env.jira
    volumes:
      - web:/var/atlassian/jira
    links:
      - jira-db
  jira-db:
    image: postgres:9.6-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira_user'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=jira_db'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=en_US.UTF-8'
      - 'POSTGRES_COLLATE_TYPE=en_US.UTF-8'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
    web:
    db:
