version: '3'

services:
  jira-web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-web
    ports:
      - 8080:8080
    env_file:
      - .env.jira
    volumes:
      - jira-web:/var/atlassian/jira
    links:
      - jira-db
  jira-db:
    restart: always
    image: postgres:11-alpine
    container_name: jira-db
    volumes:
      - jira-db:/var/lib/postgresql/jira-db
    env_file:
      - .env.db
    # environment:
      # - 'POSTGRES_USER=jira_user'
      # - 'POSTGRES_PASSWORD=password'
      # - 'POSTGRES_DB=jira_db'
      # - 'POSTGRES_ENCODING=UNICODE'
      # - 'POSTGRES_COLLATE=en_US.UTF-8'
      # - 'POSTGRES_COLLATE_TYPE=en_US.UTF-8'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

volumes:
    jira-web:
    jira-db:
